[build]
  command = "bun install && bunx prisma generate && bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment Variables
# Set these in your Netlify dashboard: Site settings > Environment variables
# Or use the Netlify CLI: netlify env:set VARIABLE_NAME "value"

# Required Environment Variables:
#
# Database (PostgreSQL)
# DATABASE_URL = "postgresql://user:password@host:5432/database?schema=public"
#
# NextAuth.js
# NEXTAUTH_SECRET = "generate-with-openssl-rand-base64-32"
# NEXTAUTH_URL = "https://your-site.netlify.app"
#
# Stripe (https://dashboard.stripe.com/test/apikeys)
# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "your_stripe_public_key"
# STRIPE_SECRET_KEY = "your_stripe_secret_key"
#
# ImageKit (https://imagekit.io/dashboard)
# NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT = "https://ik.imagekit.io/YOUR_IMAGEKIT_ID/"
# NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY = "your_public_key"
# IMAGEKIT_PRIVATE_KEY = "your_private_key"
#
# Resend Email (https://resend.com/api-keys)
# RESEND_API_KEY = "re_..."
# EMAIL_FROM = "Kollect-It <noreply@your-domain.com>"
# ADMIN_EMAIL = "admin@your-domain.com"
#
# Node Environment
# NODE_ENV = "production"
